export const AuthURL = {
  Dashboard: 'dashboard',
  Setting: 'setting',
  Profile: 'profile',
  Element: 'bootstrap-elements',
  Card: 'cards',
  Widget: 'widgets',
  Member: 'members',
  MemberCreate: 'member-create',
  Store: 'stores',
  Promotion: 'promotions',
  Managepromotion: 'manage-promotions',
  Useservice: 'use-services',
  Manageservicerequests: 'Manage-service-requests',
  Servicerequestinformation: 'Service-request-information',
  Managerefunds: 'managere-funds',
  Editmember: 'edit-members',
  Detailmember: 'detail-members',
  Addmembers: 'add-members'
};
